### ISSUE TITLE
Roleの新規作成

### ISSUE THREAD

**Issue by yoshitsugu** [yoshitsugu/holacircle#2]
今updateがあるので簡単そう

**Comment by pocari** [comment]
@yoshitsugu これやってみようと思ったので、ソース読んでいて、何点かわからなかったので理解があってるか教えて下さい

- 任意の場所に New 的なボタンがある
- Newを押したときに、今見ている(=focus) roleまた circleに紐づく新規roleの作成formができる(これは今のupdateのformで良さそう)
- （ここがよくわからず) そのときに入力している内容は
  - focusが role Xなら
    - role Xが入っているcircleに紐づくroleが新規作成される(role Xの兄弟としてroleが新規作成される)
  - focusが circle X なら
    - circle Xに紐づく(所属する)roleが新規作成される

という感じであっていますか？？(なんかホラクラシー憲法5.0をみていると ロールの中にサークルがあるような感じだったので微妙にデータ構造の正解がわかっておらず・・・)

**Comment by yoshitsugu** [comment]
@pocari サークルはロールでもあるので、基本フォーカスの円の中にサークルまたはロールが作られる、という理解で大丈夫だと思います。
データ構造的にはロールもサークルもRoleになっているので(サークルだとis_circleがtrueになる)、role_idがフォーカスしているRoleのidになっているRoleのレコードができる、という感じです

**Comment by pocari** [comment]
@yoshitsugu あ、なるほど。勝手に勘違いしていましたが、roleの中にroleができてもいいてことなんですね。ちょっとそれでrust 側も含めて見てみます！

**Comment by pocari** [comment]
@yoshitsugu PR送ろうとしたんですが、 permission denied で push 弾かれてしまったので、また権限お願いします！

**Comment by yoshitsugu** [comment]
@pocari ありがとうございます！inviteしました！

**Comment by pocari** [comment]
@yoshitsugu pushしました。 rust側もappolo側も見様見真似なのでおかしなところありそうでまたレビューお願いします！
