### ISSUE TITLE
docker-compose起動後にtimeout errorで終了する

### ISSUE THREAD

**Issue by pocari** [yoshitsugu/holacircle#3]
@yoshitsugu  cdb1340 で試してみているのですが、  クリーンビルド後でも docker-compose up で下記のようなエラーでdocker-composeが終了してしまうんですが、他に何かセットアップしておくものってありましたっけ？？

```
% docker-compose build --no-cache
...略...
% docker-compose up
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

**Comment by yoshitsugu** [comment]
@pocari 別ディレクトリにクローンしなおしてやってみましたが、DBが見つからないエラーだけでましたので、それは起動スクリプトを修正してみました。
これでも直らなければ、
https://qiita.com/Kattrxvjxxde/items/cfc689b7b204ba3b1202
これとかかも？

**Comment by pocari** [comment]
@yoshitsugu 

> これとかかも？

これでした。始めておきましたが、こういうのあるんですね・・・・。
ありがとうございます！
